[config]
schemaVersion = "0.0.1"

[package]
namespace = "Aavild"
name = "NewTerminal"
#versionNumber = "0.0.1"
description = "New Terminal for Lethal Company"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./src/Release"
target = "BepInEx/plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
categories = []

