name: Create Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: package_version
        uses: KageKirin/get-csproj-version@v0
        with:
          file: src/NewTerminal.csproj

      - name: Push to ThunderStore
        run: ./.github/tcli publish --token ${{ secrets.PUBLISH_TOKEN }} --package-version ${{ steps.package_version.outputs.version }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package_version.outputs.version }}
          artifacts: /home/runner/work/NewTerminal/NewTerminal/build/*.zip
          bodyFile: "CHANGELOG.md"
          allowUpdates: true
