name: Create Release

on:
  push:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: package_version
        uses: KageKirin/get-csproj-version@v0
        with:
          file: src/NewTerminal.csproj

      - name: Push to ThunderStore
        id: thunder_store
        uses: GreenTF/upload-thunderstore-package@v4
        with:
          namespace: Aavild
          name: NewTerminal
          version: v${{ steps.package_version.outputs.version }}
          description: "New Terminal for Lethal Company"
          categories: |
            bepinex
            mods
            misc
          deps: "BepInEx-BepInExPack-5.4.2100"
          community: lethal-company
          wrap: BepInEx/plugins
          token: ${{ secrets.PUBLISH_TOKEN }}
          path: Release/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package_version.outputs.version }}
          artifacts: output/build/*.zip
          bodyFile: "Release/CHANGELOG.md"
          allowUpdates: true
